### ISSUE TITLE
Dynamic index.html

### ISSUE THREAD

**Issue by znorman-harris** [4gray/vscode-webview-angular#1]
After finding something that I thought might be a more generic solution for prepping the HTML, I thought I would share in case it would benefit anyone else!

When you update the HTML generated by angular for the webview, instead of "sanitizing" all of the source URLs for each script/href, you can just update the HTML base tag. This way you can dynamically read the index.html from disk, update the base, and return it for rendering. I was mostly interested in doing this because the outputs from building angular apps with and without production are different, and I wanted a solution that would work for both situations. 

It is a pretty simple and small change to the HTML, which you can find here:

https://github.com/chris-torrence/vscode-idl/blob/feature/profiler/client/src/providers/idl-webview.ts#L192

**Comment by 4gray** [comment]
@znorman-harris it's a nice idea. Thank you!
